packaging_format = 2

id = "indexhibit"
name = "Indexhibit"
description.en = "Archetypal portfolio CMS for everybody"
description.fr = "CMS de portfolio archétypal pour tout le monde"

version = "2.1.2022.07.28~ynh1"

maintainers = [ "eric_G" ]

[upstream]
license = "GPL-3.0-only"
website = "https://www.indexhibit.org"
admindoc = "https://forum.indexhibit.org/tutorials/getting-started/installation/"
code = "https://github.com/Indexhibit/indexhibit"

[integration]
yunohost = ">= 11.1.15"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/indexhibit"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/Indexhibit/indexhibit/archive/c6d836b54b7e1a8a18b495e146d26894e36ac3a0.tar.gz"
        sha256 = "144ba056bf13e30622f13e6e8cf30068b16970ff4db57e17fd22f5ba2462d196"
        autoupdate.strategy = "latest_github_commit"
        autoupdate.force_version = "2.1.%Y.%m.%d"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server php8.0-fpm php8.0-mysql"

    [resources.database]
    type = "mysql"
