packaging_format = 2

id = "indexhibit"
name = "Indexhibit"
description.en = "Archetypal portfolio CMS for everybody"
description.fr = "CMS de portfolio archétypal pour tout le monde"

version = "2.1.2023.05.17~ynh2"

maintainers = [ "eric_G" ]

[upstream]
license = "GPL-3.0-only"
website = "https://www.indexhibit.org"
admindoc = "https://forum.indexhibit.org/tutorials/getting-started/installation/"
code = "https://github.com/Indexhibit/indexhibit"

[integration]
yunohost = ">= 11.1.19"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/indexhibit"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/Indexhibit/indexhibit/archive/ea0a264c5e8bf79001772950d39c6692af67643a.tar.gz"
        sha256 = "16ed14866f814f2366c44bd4e1fe6678a7d6b2fdc01145edf3202728b750b9e5"
        autoupdate.strategy = "latest_github_commit"
        autoupdate.force_version = "2.1.%Y.%m.%d"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server php8.0-fpm php8.0-mysql"

    [resources.database]
    type = "mysql"
