packaging_format = 2

id = "indexhibit"
name = "Indexhibit"
description.en = "Archetypal portfolio CMS for everybody"
description.fr = "CMS de portfolio archétypal pour tout le monde"

version = "2.1.2024.03.27~ynh1"

maintainers = [ "eric_G" ]

[upstream]
license = "GPL-3.0-only"
website = "https://www.indexhibit.org"
admindoc = "https://forum.indexhibit.org/tutorials/getting-started/installation/"
code = "https://github.com/Indexhibit/indexhibit"

[integration]
yunohost = ">= 11.2.18"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/indexhibit"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/Indexhibit/indexhibit/archive/4d37bf6cd2d8de237f3ed72b773fe9e1b4351422.tar.gz"
        sha256 = "f087b549c79aeb1a82269fdebe7f2ae6c179c6728ba84972443b0c893f7a2117"
        autoupdate.strategy = "latest_github_commit"
        autoupdate.force_version = "2.1.%Y.%m.%d"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.2-fpm, php8.2-mysql"

    [resources.database]
    type = "mysql"
